language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_cb074d786c2f_key -iv $encrypted_cb074d786c2f_iv
  -in travis_rsa.enc -out ~\/Documents/DigitalrebarTravis/travis_rsa -d
- npm i brunch -g
script:
- brunch build --production
- node_modules/.bin/gh-pages-travis
env:
  global:
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="public"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="travis_rsa"
  - GIT_NAME="travis"
  - GIT_EMAIL="deploy@travis-ci.org"
